# Generated by Django 6.0.4 on 2026-05-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('serveur', 'Serveur'), ('chef', 'Chef'), ('caissier', 'Caissier'), ('admin', 'Administrateur')], default='serveur', max_length=20),
        ),
    ]
