# Generated by Django 6.0.4 on 2026-05-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat Principal'), ('dessert', 'Dessert'), ('boisson', 'Boisson')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats/')),
            ],
        ),
    ]
