# Generated by Django 6.0.4 on 2026-05-04 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plat',
            name='image',
        ),
        migrations.CreateModel(
            name='PlatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='plats/')),
                ('is_principal', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plats.plat')),
            ],
        ),
    ]
