# Generated by Django 6.0.4 on 2026-05-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plats', '0002_remove_plat_image_platimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platimage',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='plats.plat'),
        ),
    ]
