# Generated by Django 6.0.3 on 2026-05-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Votre nom')),
                ('note', models.IntegerField(choices=[(1, '⭐ Très mauvais'), (2, '⭐⭐ Mauvais'), (3, '⭐⭐⭐ Moyen'), (4, '⭐⭐⭐⭐ Bien'), (5, '⭐⭐⭐⭐⭐ Excellent')], verbose_name='Note')),
                ('commentaire', models.TextField(verbose_name='Votre avis')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approuve', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
            },
        ),
    ]
