# Generated by Django 6.0.4 on 2026-05-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True, verbose_name='Numéro de table')),
                ('est_libre', models.BooleanField(default=True, verbose_name='Table libre')),
            ],
        ),
    ]
